name: ivory-tower-drivers
version: '0.1.0.0'
synopsis: Ivory Tower drivers
author: base48.cz
maintainer: srk@48.io
license: BSD3
dependencies:
- base >=4.6
- ivory
- ivory-stdlib
- ivory-hw
- ivory-bsp-stm32
- ivory-tower-base
- tower >=0.9
- tower-config
- tower-hal
library:
  source-dirs: src
  ghc-options: -Wall
  exposed-modules:
  - Ivory.Tower.Drivers
  - Ivory.Tower.Drivers.ADC.HX711
  - Ivory.Tower.Drivers.Display.MAX7219
  - Ivory.Tower.Drivers.Display.Fonts
  - Ivory.Tower.Drivers.Encoder.AS5407
  - Ivory.Tower.Drivers.Encoder.AS5407.Regs
  - Ivory.Tower.Drivers.Encoder.AS5407.Types
  - Ivory.Tower.Drivers.Net.RN2483
  - Ivory.Tower.Drivers.Temperature.Types
  - Ivory.Tower.Drivers.Temperature.HTS221
  - Ivory.Tower.Drivers.Temperature.HTS221.Peripheral
  - Ivory.Tower.Drivers.Temperature.HTS221.Regs
  - Ivory.Tower.Drivers.Temperature.HTS221.RegTypes
  - Ivory.Tower.Drivers.GPS.NMEA
    # - Ivory.Tower.Drivers.PWM.ATIM
  dependencies:
  - bytestring
  - dlist
  - monadLib
  - ivory-serialize
#executables:
#  rn2483-test-gen: &apptemplate
#    main:                RN2483Test.hs
#    source-dirs:         test
#    other-modules:
#    - TestPlatforms
#    ghc-options: -Wall
#    dependencies:
#    - ivory-backend-c
#    - tower-freertos-stm32
#      #    - ivory-bsp-tests
#    - ivory-tower-drivers
#  max7219-test-gen:
#    <<: *apptemplate
#    main:                MAX7219Test.hs
#  hx711-test-gen:
#    <<: *apptemplate
#    main:                HX711Test.hs
#  as5407-test-gen:
#    <<: *apptemplate
#    main:                AS5407Test.hs
